# Generated by Django 2.1 on 2018-08-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_type', models.IntegerField(default=0)),
                ('key_value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Threadcheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_time', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Threadlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href', models.CharField(default='', max_length=100, null=True)),
                ('content', models.TextField(default='', max_length=999, null=True)),
                ('username', models.CharField(max_length=50, null=True, verbose_name='发帖人昵称')),
                ('title', models.TextField(null=True, verbose_name='帖子标题')),
                ('insert_time', models.DateTimeField(verbose_name='记录到数据库的时间（近似与发帖时间）')),
                ('from_site', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='threadcheck',
            name='have_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threadlist.Threadlist'),
        ),
    ]
